// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE3c5uRNPA0tKI3g4fJui_vmmfYeMJh-U',
    appId: '1:84094227270:web:ad96c047c46a1c92580b47',
    messagingSenderId: '84094227270',
    projectId: 'jadwalkuliah-27c98',
    authDomain: 'jadwalkuliah-27c98.firebaseapp.com',
    storageBucket: 'jadwalkuliah-27c98.firebasestorage.app',
    measurementId: 'G-071Y040KQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRqmVbb__1JI8ZkPKuBjqmtylq7dp_a8',
    appId: '1:84094227270:android:6c1c0de80a6154a1580b47',
    messagingSenderId: '84094227270',
    projectId: 'jadwalkuliah-27c98',
    storageBucket: 'jadwalkuliah-27c98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBkvOz3R5leAv719XfSmqLhuECrWyCQEo',
    appId: '1:84094227270:ios:e420e8df1c39f930580b47',
    messagingSenderId: '84094227270',
    projectId: 'jadwalkuliah-27c98',
    storageBucket: 'jadwalkuliah-27c98.firebasestorage.app',
    iosBundleId: 'com.example.jadwalkuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBkvOz3R5leAv719XfSmqLhuECrWyCQEo',
    appId: '1:84094227270:ios:e420e8df1c39f930580b47',
    messagingSenderId: '84094227270',
    projectId: 'jadwalkuliah-27c98',
    storageBucket: 'jadwalkuliah-27c98.firebasestorage.app',
    iosBundleId: 'com.example.jadwalkuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE3c5uRNPA0tKI3g4fJui_vmmfYeMJh-U',
    appId: '1:84094227270:web:ee96da0485f023d0580b47',
    messagingSenderId: '84094227270',
    projectId: 'jadwalkuliah-27c98',
    authDomain: 'jadwalkuliah-27c98.firebaseapp.com',
    storageBucket: 'jadwalkuliah-27c98.firebasestorage.app',
    measurementId: 'G-E3QLFP6L92',
  );
}
