// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhnIt8ORG90X84zxnG-JkMeX1gd9rdEo',
    appId: '1:754197844127:web:c516b8110aba2f442012aa',
    messagingSenderId: '754197844127',
    projectId: 'notes-f2f9b',
    authDomain: 'notes-f2f9b.firebaseapp.com',
    storageBucket: 'notes-f2f9b.firebasestorage.app',
    measurementId: 'G-G42BPMHX77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WruZRD7ndd8pqg9HY1blkXKeUnJTOGI',
    appId: '1:754197844127:android:7e37f57dd9733e5f2012aa',
    messagingSenderId: '754197844127',
    projectId: 'notes-f2f9b',
    storageBucket: 'notes-f2f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcSm4KU4sHX6bXfFMvTWTYaHeOZrJFCGM',
    appId: '1:754197844127:ios:0c2106b54ca59d842012aa',
    messagingSenderId: '754197844127',
    projectId: 'notes-f2f9b',
    storageBucket: 'notes-f2f9b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcSm4KU4sHX6bXfFMvTWTYaHeOZrJFCGM',
    appId: '1:754197844127:ios:0c2106b54ca59d842012aa',
    messagingSenderId: '754197844127',
    projectId: 'notes-f2f9b',
    storageBucket: 'notes-f2f9b.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhnIt8ORG90X84zxnG-JkMeX1gd9rdEo',
    appId: '1:754197844127:web:b0ffd71b790405592012aa',
    messagingSenderId: '754197844127',
    projectId: 'notes-f2f9b',
    authDomain: 'notes-f2f9b.firebaseapp.com',
    storageBucket: 'notes-f2f9b.firebasestorage.app',
    measurementId: 'G-KGZBM8L3SZ',
  );
}
