// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsfnJ3sdNwbEqVWEB1C0nTH8HuEiepLZw',
    appId: '1:845730363441:web:f5e7e3390330415f443d10',
    messagingSenderId: '845730363441',
    projectId: 'daftarbelanja-551e4',
    authDomain: 'daftarbelanja-551e4.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-551e4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-551e4.firebasestorage.app',
    measurementId: 'G-C0QYM0S6NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCxDYaAl3-z9HZPZRVLzjOAf0H3DM6DAI',
    appId: '1:845730363441:android:29fbfdd221bc7f23443d10',
    messagingSenderId: '845730363441',
    projectId: 'daftarbelanja-551e4',
    databaseURL: 'https://daftarbelanja-551e4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-551e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_5w4hdKblYhwW0gA7qh2zBcDhzi12JSo',
    appId: '1:845730363441:ios:c3cd4ddd85e637c7443d10',
    messagingSenderId: '845730363441',
    projectId: 'daftarbelanja-551e4',
    databaseURL: 'https://daftarbelanja-551e4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-551e4.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_5w4hdKblYhwW0gA7qh2zBcDhzi12JSo',
    appId: '1:845730363441:ios:c3cd4ddd85e637c7443d10',
    messagingSenderId: '845730363441',
    projectId: 'daftarbelanja-551e4',
    databaseURL: 'https://daftarbelanja-551e4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-551e4.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsfnJ3sdNwbEqVWEB1C0nTH8HuEiepLZw',
    appId: '1:845730363441:web:88532bd5f1b5a69a443d10',
    messagingSenderId: '845730363441',
    projectId: 'daftarbelanja-551e4',
    authDomain: 'daftarbelanja-551e4.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-551e4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-551e4.firebasestorage.app',
    measurementId: 'G-05EHDKGBM1',
  );
}
