// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuSjjbxCoUJpO1Z1eoVHzj2iMGQ30SYhw',
    appId: '1:906855616300:web:adb25939bf81dadf222689',
    messagingSenderId: '906855616300',
    projectId: 'mdpgold-cde3d',
    authDomain: 'mdpgold-cde3d.firebaseapp.com',
    databaseURL: 'https://mdpgold-cde3d-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cde3d.firebasestorage.app',
    measurementId: 'G-1WB66PS9WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSsaYTgTJVxIfsP1fvAE5e3oEYlmEaKmQ',
    appId: '1:906855616300:android:49998352ac9b6014222689',
    messagingSenderId: '906855616300',
    projectId: 'mdpgold-cde3d',
    databaseURL: 'https://mdpgold-cde3d-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cde3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEakXHGIK7kLpUTmwVfsVKW22gSBuw78A',
    appId: '1:906855616300:ios:dd7f39ce9fe87217222689',
    messagingSenderId: '906855616300',
    projectId: 'mdpgold-cde3d',
    databaseURL: 'https://mdpgold-cde3d-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cde3d.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEakXHGIK7kLpUTmwVfsVKW22gSBuw78A',
    appId: '1:906855616300:ios:dd7f39ce9fe87217222689',
    messagingSenderId: '906855616300',
    projectId: 'mdpgold-cde3d',
    databaseURL: 'https://mdpgold-cde3d-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cde3d.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuSjjbxCoUJpO1Z1eoVHzj2iMGQ30SYhw',
    appId: '1:906855616300:web:18ea1a6327418a6c222689',
    messagingSenderId: '906855616300',
    projectId: 'mdpgold-cde3d',
    authDomain: 'mdpgold-cde3d.firebaseapp.com',
    databaseURL: 'https://mdpgold-cde3d-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-cde3d.firebasestorage.app',
    measurementId: 'G-MEF3Q23BFM',
  );
}
